version: '3.6'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: faberchri/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:                        # post mapping
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI    -- 127.0.0.1:3030
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker

      # git clone https://github.com/faberchri/fast-data-dev.git
      # cd fast-data-dev
      # docker build -t faberchri/fast-data-dev .
      # docker run --rm -p 3030:3030 faberchri/fast-data-dev

  # we will use elasticsearch as one of our sinks.
  # This configuration allows you to start elasticsearch
  # run below and start it at Docker desktop
  # docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.10.2
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      PLUGINS: appbaseio/dejavu
      OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
    ports:
      - "9200:9200"

  # we will use postgres as one of our sinks.
  # This configuration allows you to start postgres
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432                 # Postgres port
  
  # search engine
  opensearch:
      image: opensearchproject/opensearch:1.2.4
      container_name: opensearch
      environment:
          - plugins.security.disabled=true
          - discovery.type=single-node
          - http.port=9200
          - http.cors.enabled=true
          - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
          - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
          - http.cors.allow-credentials=true
          - bootstrap.memory_lock=true
          - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      ports:
          - '9200:9200'
      ulimits:
          memlock:
              soft: -1
              hard: -1
      volumes:
          - ./data:/usr/share/opensearch/data
  # elasticsearch browser
  dejavu:
      image: appbaseio/dejavu:3.6.0
      container_name: dejavu
      ports:
          - '1358:1358'
      links:
          - opensearch
