version: '3.7'
services: # double click on the double arrow,
  opensearch:
    image: opensearchproject/opensearch:1.2.4 # database
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true" # disable https and logins
      compatibility.override_main_response_version: "true"
    ports:
      - 9200:9200 # to check if it's working go to http://localhost:9200/
      - 9600:9600 # required for Performance Analyzer

  # console at http://localhost:5601/app/dev_tools#/console
  #

  # run rest api queries against Elasticsearch - tutorials for the command above
  # https://opensearch.org/docs/latest/#docker-quickstart
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    ports:
      - 5601:5601 # to check if it's working go to http://localhost:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"