version: '3.6'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: faberchri/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:                        # post mapping
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI    -- 127.0.0.1:3030
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker


# docker-compose up
# http://localhost:3030/